
Z -> B  
B -> TIPO_CREATE TIPO_TABLE ID LPAREN C ID D C RPAREN PUNTOYCOMA
B -> TYPO_DROP TIPO_TABLE ID PUNTOYCOMA
B -> TYPO_SELECT COMODIN TYPO_FROM ID TYPO_WHERE E PUNTOYCOMA
B -> TYPO_CREATE TYPO_PROCEDURE ID LPAREN PMARCA G L RPARENT TYPO_AS TYPO_BEGIN TYPO_INSERT TYPO_INTO ID K TYPO_EVAL W PUNTOYCOMA TYPO_END PUNTOYCOMA
C -> COMA ID D
C -> ''
D -> TIPO_INT LPAREN NUM RPAREN
D -> TIPO_VARCHAR

K -> LPAREN ID U RPAREN
K -> ''
U -> COMA ID U
U -> ''

W -> LPAREN PMARCA X RPAREN
W -> ''
X -> COMA PMARCA X
X -> ''

L -> COMA PMARCA J
L -> ''
J -> G L

E -> T E'
E' -> MAS T E'
E' -> MENOS T E'
E' -> DIVIDE T E'
E' -> MENOR T E'
E' -> MAYOR T E'
E' -> IGUAL T E'
E' -> MAYORIGUAL T E'
E' -> MENORIGUAL T E'
E' -> AND T E'
E' -> OR T E'
E' -> NOT T E'
E' -> ''
T -> F T'
T' -> * F T'
T' -> ''
F -> ( E )
F -> NUM
F -> DOUBLE
F -> ID
G -> TIPO_CADENAVAR LPAREN NUM RPAREN
G -> TIPO_DECIMAL LPAREN DECIMAL RPAREN
G -> TIPO_DECIMAL LPAREN DECIMAL RPAREN
